// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: todo.sql

package db

import (
	"context"
)

const getTodos = `-- name: GetTodos :many
SELECT id, task, completed FROM todoList ORDER BY id
`

func (q *Queries) GetTodos(ctx context.Context) ([]Todolist, error) {
	rows, err := q.db.QueryContext(ctx, getTodos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todolist
	for rows.Next() {
		var i Todolist
		if err := rows.Scan(&i.ID, &i.Task, &i.Completed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
